import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';

const GENERATED_HEADER = `// AUTO-GENERATED by pnpm regen (prisma-merge). Do not edit directly.
// Source: packages/modules/*/prisma.partial.prisma + infra/prisma/base.prisma
`;

export async function mergePrismaPartials(opts: {
  repoRoot: string;
  modulesDir?: string;
  /**
   * Extra directories whose immediate subfolders may each contain a
   * `prisma.partial.prisma`. Lets a downstream consumer fold its own plugin
   * tables (eg `consumer/plugins`) into the merged schema without touching OSS
   * partials. Default-empty, so OSS behavior is unchanged.
   */
  extraDirs?: string[];
  baseFile?: string;
  outputFile?: string;
  /** Label paths relative to this root in the merged file's comments. */
  pathRoot?: string;
}): Promise<void> {
  const {
    repoRoot,
    modulesDir = join(repoRoot, 'packages', 'modules'),
    extraDirs = [],
    baseFile = join(repoRoot, 'infra', 'prisma', 'base.prisma'),
    outputFile = join(repoRoot, 'infra', 'prisma', 'schema.prisma'),
    pathRoot = repoRoot,
  } = opts;

  const parts: string[] = [GENERATED_HEADER];

  const base = await readFile(baseFile, 'utf8').catch(() => '');
  if (base) parts.push(base);

  const partialFiles: string[] = [];
  for (const dir of [modulesDir, ...extraDirs]) {
    const entries = await readdir(dir, { withFileTypes: true }).catch(() => []);
    for (const entry of entries) {
      if (!entry.isDirectory()) continue;
      partialFiles.push(join(dir, entry.name, 'prisma.partial.prisma'));
    }
  }

  for (const partialPath of partialFiles.sort()) {
    const content = await readFile(partialPath, 'utf8').catch(() => null);
    if (!content?.trim()) continue;
    parts.push(`// -- ${resolve(partialPath).replace(pathRoot + '/', '')} --`);
    parts.push(content.trim());
  }

  await writeFile(outputFile, parts.join('\n\n') + '\n', 'utf8');
}
