packages:
  - 'apps/*'
  - 'packages/*/*'
  - 'packages/sdks/react-sdk/examples/*'
  - 'infra'
allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  sharp: true
