import { createRouter as createTanStackRouter } from '@tanstack/react-router';
import { routeTree } from './routeTree.gen';

// TanStack Start picks up this factory to build a fresh router per request (SSR)
// and once on the client. The route tree is generated by the Start Vite plugin
// from src/routes/** into src/routeTree.gen.ts (gitignored).
export function createRouter() {
  return createTanStackRouter({
    routeTree,
    defaultPreload: 'intent',
    scrollRestoration: true,
  });
}

declare module '@tanstack/react-router' {
  interface Register {
    router: ReturnType<typeof createRouter>;
  }
}
