# {{Name}} Module - AGENTS.md

Generated by `/scaffold-module {{name}}`. Fill in all sections before opening a PR.

## What this module does

<!-- One paragraph. What business domain does this own? What problem does it solve? -->

## Extension points

### Ports (adapter interfaces)
- Define vendor interfaces + their DI token in `@oss/adapters` (`packages/contracts/adapters/src/<category>.ts`), then `@Inject` the token in your service. Add concrete implementations under `src/adapters/<vendor>/` and bind them to the token in `plugin.ts`.

| Interface | Symbol | Purpose |
|---|---|---|
| <!-- `{{Name}}Provider` --> | <!-- `{{NAME_UPPER}}_PROVIDER` --> | <!-- e.g. external API calls --> |

### Events emitted
| Event type | Payload | When |
|---|---|---|
| <!-- `{{name}}:created` --> | <!-- `{ id, tenantId }` --> | <!-- on creation --> |

### Events consumed
| Event type | Handler | Why |
|---|---|---|
| <!-- `identity:user-deleted` --> | <!-- cleanup --> | <!-- cascade deletes --> |

### UI slots filled
| Slot name | Component | Where it appears |
|---|---|---|
| <!-- `sidebar-bottom` --> | <!-- `{{Name}}SidebarItem` --> | <!-- backoffice sidebar --> |

### oRPC routes
| Procedure | Method | Path | Auth required |
|---|---|---|---|
| <!-- `{{name}}.list` --> | GET | <!-- `/{{name}}s` --> | <!-- yes --> |

## Do

- Add business logic to `service/{{name}}.service.ts`.
- New Zod schemas in `schemas/index.ts` or promote to `@oss/shared-schemas` if shared.
- New Drizzle tables in `src/schema/index.ts`, then `pnpm regen` (drizzle-kit).
- Add routes via `/scaffold-route {{name}} <method> <path>`.
- If adding a third-party dependency, add it to the single `packages/modules/package.json`.
- If adding a vendor dependency: define a port interface + inject adapter via Nest DI.

## Don't

- Import from other modules directly. Use EventBus or contracts. (Cross-module table reads go through `@oss/modules/<group>/<name>/schema`.)
- Add vendor SDK calls directly in the service. Define a port.
- Throw `HttpException` from the service. Throw domain errors.
- Add a per-module `package.json` or `tsconfig.json` - modules share the single `@oss/modules` package.
- Add `z.any()` or hand-written TypeScript interfaces for schemas.

## Sample diff - adding a route

```diff
// src/router/index.ts
+ list: os
+   .input(PaginationSchema)
+   .output(z.array({{Name}}Schema))
+   .handler(async ({ input, context }) => {
+     return context.{{name}}Service.list(input);
+   }),
```

Add the handler in `service/{{name}}.service.ts` and run `pnpm regen && pnpm verify`.

## Sample diff - adding an event

```diff
// src/service/{{name}}.service.ts
+ this.eventBus.emit('{{name}}:created', { id: result.id, tenantId });
```

Register the event type in `@oss/core` (`event-bus.ts`).
