# {{Name}} Module - AGENTS.md

Generated by `/scaffold-module {{name}}`. Fill in all sections before opening a PR.

## What this module does

<!-- One paragraph. What business domain does this own? What problem does it solve? -->

## Extension points

### Ports (adapter interfaces)
- `src/service/ports.ts` - define vendor interfaces here. Add implementations under `src/adapters/<vendor>/`.

| Interface | Symbol | Purpose |
|---|---|---|
| <!-- `{{Name}}Provider` --> | <!-- `{{NAME_UPPER}}_PROVIDER` --> | <!-- e.g. external API calls --> |

### Events emitted
| Event type | Payload | When |
|---|---|---|
| <!-- `{{name}}:created` --> | <!-- `{ id, tenantId }` --> | <!-- on creation --> |

### Events consumed
| Event type | Handler | Why |
|---|---|---|
| <!-- `identity:user-deleted` --> | <!-- cleanup --> | <!-- cascade deletes --> |

### UI slots filled
| Slot name | Component | Where it appears |
|---|---|---|
| <!-- `sidebar-bottom` --> | <!-- `{{Name}}SidebarItem` --> | <!-- backoffice sidebar --> |

### oRPC routes
| Procedure | Method | Path | Auth required |
|---|---|---|---|
| <!-- `{{name}}.list` --> | GET | <!-- `/{{name}}s` --> | <!-- yes --> |

## Do

- Add business logic to `service/{{name}}.service.ts`.
- New schemas in `schemas/index.ts` or promote to `@oss/contracts/domain-schemas` if shared.
- Add routes via `/scaffold-route {{name}} <method> <path>`.
- New tables in `prisma.partial.prisma`, then `pnpm regen`.
- If adding a vendor dependency: define a port interface + inject adapter via Nest DI.

## Don't

- Import from other modules directly. Use EventBus or contracts.
- Add vendor SDK calls directly in the service. Define a port.
- Throw `HttpException` from the service. Throw domain errors.
- Edit `infra/prisma/schema.prisma` - it's overwritten by `pnpm regen`.
- Add `z.any()` or hand-written TypeScript interfaces for schemas.

## Sample diff - adding a route

```diff
// src/router/index.ts
+ list: os
+   .input(PaginationSchema)
+   .output(z.array({{Name}}Schema))
+   .handler(async ({ input, context }) => {
+     return context.{{name}}Service.list(input);
+   }),
```

Add the handler in `service/{{name}}.service.ts` and run `pnpm regen && pnpm verify`.

## Sample diff - adding an event

```diff
// src/service/{{name}}.service.ts
+ this.eventBus.emit('{{name}}:created', { id: result.id, tenantId });
```

Register the event type in `packages/platform/events/src/types.ts`.
